development:
  adapter: postgresql
  database: football_development
  pool: 5
  host: 198.199.109.47
  username: postgres
  password: slar177
  timeout: 5000


development:
  adapter: postgresql
  database: football_test
  pool: 5
  host: 198.199.109.47
  username: postgres
  password: slar177
  timeout: 5000

development:
  adapter: postgresql
  database: football_production
  pool: 5
  host: 198.199.109.47
  username: postgres
  password: slar177
  timeout: 5000